### ISSUE TITLE
AttributeError: 'Bleno' object has no attribute 'setAdvertisingParams'

### ISSUE THREAD

**Issue by spaetz** [mh-/exposure-notification-ble-python#2]
Hi,
I did install the git version of https://github.com/mh-/pybleno. But I get:

```
TX: BDADDR should roll...
CRYPTO: padded data: 454e2d52504900000000000057802800 --> RPI: 0d00541f3e106fc3dc69a3c9d7ccf64e
CRYPTO: metadata: 400c0000 --> AEM: e1140345
BLE TX: RPI: 0d00541f3e106fc3dc69a3c9d7ccf64e, AEM: e1140345, BDADDR: 21870d7e9825
Traceback (most recent call last):
  File "en_beacon.py", line 124, in <module>
    beacon = ENBeacon(rpi=_rpi, aem=_aem, bdaddr=_bdaddr)
  File "en_beacon.py", line 27, in __init__
    self.set_en_advertising_parameters()  # this will be successful only before bleno is poweredOn.
  File "en_beacon.py", line 58, in set_en_advertising_parameters
    self.bleno.setAdvertisingParams(advertisementIntervalMin=200 * 1000 // 625,
AttributeError: 'Bleno' object has no attribute 'setAdvertisingParams'
Traceback (most recent call last):
  File "exposure-notification.py", line 112, in <module>
    tx_service.start_beacon(rpi=crypto.rpi, aem=crypto.aem)
  File "/home/mobian/exposure-notification-ble-python/lib/en_tx_service.py", line 52, in start_beacon

```

And looking at both your clone and Adam Langley's pybleno (which do not deviate anymore btw), that method does indeed not seem to exist.

**Comment by mh-** [comment]
Did you explicitly use the enhancements-for-exposure-notification branch?
requirements.txt lists:
git+git://github.com/mh-/pybleno.git@enhancements-for-exposure-notification#egg=pybleno

**Comment by spaetz** [comment]
Doh. Used master, will retest, Sorry.

**Comment by mh-** [comment]
I think that using the specific branch should solve this, otherwise please re-open.
